### ISSUE TITLE
Basic http server

### ISSUE THREAD

**Issue by waldo121** [ClubCedille/presence-detector-api#1]
Faire un serveur http répondant aux appels http GET sur l'endpoint /api/v1/presence.

**Comment by waldo121** [comment]
Paramètres de la requête:
Basic authentification

**Comment by waldo121** [comment]
HTTPS n'est pas requis car il n'y a aucune donnée sensible dans les données que l'on transfère.

**Comment by waldo121** [comment]
Il doit être containerizé à l'aide d'un Dockerfile.

**Comment by AXDOOMER** [comment]
La lumière est on: https://aquinas.xyz/club/api.php?boolSet=1
La lumière est off: https://aquinas.xyz/club/api.php?boolSet=0
Voir la valeur: https://aquinas.xyz/club/api.php

**Comment by waldo121** [comment]
Je close l'issue puisque le code a été mergé.
